# Generated by Django 4.2.3 on 2023-07-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='item3',
        ),
    ]
