# Generated by Django 4.2.3 on 2023-07-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_alter_risto_descrizione_alter_risto_item1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='sito',
        ),
        migrations.RemoveField(
            model_name='risto',
            name='sito',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='item1',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='risto',
            name='descrizione',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
