# Generated by Django 4.2.3 on 2023-07-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_remove_hotel_sito_remove_risto_sito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='risto',
            name='contact',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
