# Generated by Django 4.2.3 on 2023-07-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_hotel_contact_risto_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='risto',
            name='contact',
        ),
    ]
