# Generated by Django 4.2.3 on 2023-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('titolo', models.CharField(default=None, max_length=20)),
                ('descrizione', models.TextField()),
                ('firma', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
